### ISSUE TITLE
Errors as of Three.js r112

### ISSUE THREAD

**Issue by JustASquid** [Jam3/three-bmfont-text#34]
Looks like some deprecations have caused some warnings/errors.

`THREE.BufferAttribute: .setArray has been removed. Use BufferGeometry .setAttribute to replace/resize attribute buffers`

`THREE.BufferGeometry: .addAttribute() has been renamed to .setAttribute().`

**Comment by mikehenrty** [comment]
I believe this will need to be fixed upstream:
https://github.com/Jam3/three-buffer-vertex-data/issues/3

A fixed was proposed, but I haven't tested it:
https://github.com/Jam3/three-buffer-vertex-data/compare/master...ilidio:master

**Comment by FredericBriolet** [comment]
Hi all,

I'm using three.js r114, and indeed the erros come from three-buffer-vertex-data. I tried using Ilidio's version of three-buffer-vertex-data, errors were gone but the text wasn't visible (maybe I was doing something wrong).

Anyway I used this fork of three-bmfont-text instead and it worked nicely:
https://github.com/dmarcos/three-bmfont-text

It uses another fork of three-buffer-vertex-data:
https://github.com/dmarcos/three-buffer-vertex-data

Just replaced three-bmfont-text in my package.json:
from: `"three-bmfont-text": "^2.3.0"`
to: `"three-bmfont-text": "dmarcos/three-bmfont-text#1babdf8507"`

Thanks dmarcos!

**Comment by HexaField** [comment]
I have created some pull requests that fix these issues.

**Comment by mattdesl** [comment]
Thanks, this is finally fixed in version 3. I had to bump as a major since it proved too difficult to support both new and old versions of ThreeJS simultaneously, which is why this issue dragged on so long. One downside is that with the newer version of ThreeJS, you have to re-create typed arrays to update text, instead of having the possibility of modifying an existing typed array.
